AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  language_lessons

  Sample SAM Template for language_lessons

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 300
    MemorySize: 128

Resources:
  TranslateFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: translate_text/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        Translate:
          Type: Api
          Properties:
            Path: /translate
            Method: post
            RestApiId:
              Ref: ApiGatewayApi
  SpeakFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: speak/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        Speak:
          Type: Api
          Properties:
            Path: /speak
            Method: post
            RestApiId:
              Ref: ApiGatewayApi
  OtherFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: transcribe/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        Other:
          Type: Api
          Properties:
            Path: /transcribe
            Method: post
            RestApiId:
              Ref: ApiGatewayApi
  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: dev
      Cors:
        AllowMethods: "'POST, OPTIONS'"
        AllowOrigin: "'*'"
        AllowHeaders: "'Content-Type,Authorization,X-Amz-Date,X-Api-Key,X-Amz-Security-Token'"
        AllowCredentials: true
        Connection: "keep-alive"
